#!/bin/bash
echo "Enter folder name: "
read folder

mkdir $folder
for file in `find ./ -type f -name "*.php"`
do
    fileFolder=${file%.*}
    echo $fileFolder
    mkdir ./$folder/$fileFolder
    cp -p ./$file ./$folder/$fileFolder/$file
done
echo `ls`
getch=""